mainSections:
  - posts
description: Vous trouverez sur ce site l'avancement des side projects et reflexions de Timothée DORAND.

repoEditURL:

dateFormat:

homeInfoParams:
  Title: From Paris to Berlin
    # Content: Je suis développeur web fullstack, diplômé de <a href="https://iim.fr">l'IIM</a> en 2019 et responsable de l'espace Carte Bancaire en ligne chez Société Générale jusqu'en 2024. Pendant mon temps libre, je m'occupe du site et de la programmation de ma propre émission chez la webradio <a href="https://www.radio-sofa.com">Radio Sofa</a>.
  Content: >
    Web developper during the day and musician and at night. 
    Learn more about me in the <a href="/posts/about" >About page.</a>
    <br/> <i>Développeur web le jour et musicien la nuit. 
    En savoir plus sur la <a href="/posts/about" >page A propos.</a> </i>
    <br/><br/>Please find below my latests projects. 
    <br><i>Vous trouverez ci-dessous mes derniers projets.</i>
socialIcons:
  - name: soundcloud
    url: https://soundcloud.com/janastasiamusic
  - name: linkedin
    url: https://www.linkedin.com/in/timotheedorand/
  - name: github
    url: https://github.com/TimDorand

titleSeparator:

# Options: auto, light and dark. Default is auto.
colorScheme:

# Colors and fonts. Default style is data/styles/default.yaml/
style:

# E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
siteType: Person
icon:
publisherName: Timothée DORAND
publisherLogo:

highlight:
  handler: highlightjs

  highlightjs:
    # highlight.js doesn't bundle every language. So please specify additional languages you want here.
    # See https://github.com/highlightjs/cdn-release/tree/main/build/languages for available languages.
    languages:
      - dart
    # See https://github.com/highlightjs/cdn-release/tree/main/build/styles for available styles.
    style: base16/solarized-light

math:
  handler: katex

  # katex:
  #   # Browse https://katex.org/docs/options.html to see the options available.
  #   # KaTeX's Auto-render ignores `displayMode` property of the options, so this property will not work.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `throwOnError` should be written as `throw-On-Error` or other acceptable formats.
  #   leqno:

comment:
  # Options: disqus, commento, valine and utterances.
  handler:

  # disqus:
  #   shortname:

  # utterances:
  #   # Browse https://utteranc.es/ to see the options available.
  #   # If you want the color scheme of utterances to follow eureka's, you can set `theme: eureka`.
  #   repo:
  #   issue-term:
  #   theme:

  # commento:
  #   # If self-hosting, please enter the url (e.g. https://commento.example.com) here. Otherwise leave empty.
  #   url:

  # valine:
  #   # Browse https://valine.js.org/en/configuration.html to see the options available.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `appId` should be written as `app-Id` or other acceptable formats.
  #   app-Id:
  #   app-Key:

diagram:
  handler: mermaid

  # mermaid:
  #   # Browse https://mermaid-js.github.io/mermaid/#/Setup to see the options available.
  #   # You can list the key and value you want as below.
  #   # Because Hugo's config params are case-insensitive, you need to add `-` or `_` before the uppercase letters.
  #   # For example, `diagramPadding` should be written as `diagram-Padding` or other acceptable formats.
  #   theme:
  #   flowchart:
  #     diagram-padding:
